# The workflow will build a Forge Mod with Gradle
# then upload it to the github releases tab
#
# creator: boomboompower
# version: 1.0

name: Mod Deployment CI

# Trigger the integration for pull requests and pushes
# to every branch on the repository
on:
  push:
    paths:
      - src/**
      - ToggleChat/src**
      - build.gradle

jobs:
  linux:
    name: Linux Mod CI

    # Use latest linux distro
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Commit message
        id: com-mess
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }} 
        run: |
           echo ::set-output name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
           echo "${{ github.run_number }}" > ./ToggleChat/src/main/resources/GHCI.txt
           echo "${{ github.sha }}" > ./ToggleChat/src/main/resources/commit.txt

        # Required so gradlew can build the JAR file
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

        # Sets up the forge workspace (using CI)
      - name: Launch Forge Workspace
        run: ./gradlew setupCIWorkspace clean

        # Deletes any unnecessary files which shouldn't
        # exist in the first place.
      - name: Clean output directories
        run: |
          rm -f -R out
          rm -f -R build

        # Uses ForgeGradle to build the jar
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Calculate Hashes
        id: hashes
        run: |
          echo ::set-output name=program_hash::$(sha256sum ./ToggleChat/build/libs/ToggleChat.jar | cut -d ' ' -f 1)
          echo ::set-output name=source_hash::$(sha256sum ./ToggleChat/build/libs/ToggleChat-sources.jar | cut -d ' ' -f 1)

      # Upload the main mod to the releases tab
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 3.0.${{ github.run_number }}
          release_name: Beta Release ${{ github.run_number }} (3.0.${{ github.run_number }})
          body: |
            ### ToggleChat Beta 3.0.${{ github.run_number }}
            > Huh, nothing here?
            
            ```
            ${{ steps.com-mess.outputs.commitmsg }}
            ```

            ### Next up
            > What's on the roadmap?
            
            It seems quiet... Too quiet...

            ### Installation

            ##### Using the installer:
            1. Download "ToggleChat.jar"
            2. Double click the file
            3. Go through the installer
            4. Run the game

            ##### Manual install:
            1. Install [Forge for 1.8.9](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.8.9.html)
            2. [Locate .minecraft](https://help.minecraft.net/hc/en-us/articles/360035131551-Where-are-Minecraft-files-stored) folder
            3. Download the "ToggleChat.jar" to your ".minecraft/mods/1.8.9" directory
            4. Run the game


            ### Hashes
            > Don't install untrusted files
            * ToggleChat: `${{ steps.hashes.outputs.program_hash }}`
            * ToggleChat-sources: `${{ steps.hashes.outputs.source_hash }}`
            
            Automagically generated with lots of ❤
          draft: false
          prerelease: true
      - name: Upload Mod
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: './ToggleChat/build/libs/ToggleChat.jar'
          asset_name: ToggleChat.jar
          asset_content_type: application/zip
      - name: Upload Mod Sources
        id: upload-sources-asset 
        uses: actions/upload-release-asset@v1
        
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: './ToggleChat/build/libs/ToggleChat-sources.jar'
          asset_name: ToggleChat-sources.jar
          asset_content_type: application/zip
